[package]
name = "nemopi-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rumqttc = "0.23.0"
base64 = "0.21.5"
hmac = "0.12"
sha2 = "0.10"
chrono = "0.4"
serde_urlencoded = "0.7"